repos:
-   repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
    - id: black
      additional_dependencies: ['click==8.0.4']
      language_version: python3.11
      args:
        - --config=pyproject.toml
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.0.1'
    hooks:
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
-   repo: https://github.com/PyCQA/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: [-settings-path, setup.cfg]
-   repo: https://github.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
        args: [--config, setup.cfg]
-   repo: https://github.com/pycqa/pylint
    rev: v2.16.2
    hooks:
    - id: pylint
      args: [--disable=all, --enable=unused-import]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        additional_dependencies: [types-all, sqlalchemy-stubs]
        exclude: 'scripts/'
-   repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest -v
      language: python
      pass_filenames: false
      always_run: true
