db_connection_string: "Driver={ODBC Driver 17 for SQL Server};Server=DESKTOP-AKTLEQ8;Database=sampledb;UID=sa;PWD=klop09;Encrypt=yes;TrustServerCertificate=yes;Connection Timeout=30;"
api:
  host: "0.0.0.0"
  port: "8080"
slack:
  webhook_url: "https://hooks.slack.com/services/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"
  token: "xoxb-755692202805-5096311761875-JvT73F40x8pV2GBGQlQmtNjb"
  channel: "dev_test"
log:
  version: 1
  disable_existing_loggers: no
  formatters:
    formatter:
      format: "[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s"
  handlers:
    console_handler:
      class: logging.StreamHandler
      level: DEBUG
      formatter: formatter
      stream: ext://sys.stdout
    file_handler:
      class: logging.FileHandler
      level: INFO
      formatter: formatter
      filename: logfile.log
  loggers:
    root:
      level: DEBUG
      handlers:
        - console_handler
        - file_handler
